# yamllint configuration for Bento YAML config files
# https://yamllint.readthedocs.io/en/stable/configuration.html

---
extends: default

# Files to lint
yaml-files:
  - '*.yaml'
  - '*.yml'
  - 'bento/**/*.yaml'
  - 'bento/**/*.yml'
  - '.github/**/*.yaml'
  - '.github/**/*.yml'

# Ignore files
ignore: |
  /vendor/
  /.git/
  /build/
  /dist/

rules:
  # Line length - Bento configs can be long, be flexible
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true

  # Indentation - Bento uses 2 spaces
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false

  # Comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: true
    ignore-shebangs: true

  # Trailing spaces
  trailing-spaces: enable

  # Empty lines
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0

  # Document markers
  document-start:
    present: false  # Don't require --- at start of file

  document-end:
    present: false  # Don't require ... at end of file

  # Brackets and braces
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  # Colons
  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  # Commas
  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  # Hyphens (list items)
  hyphens:
    max-spaces-after: 1

  # Empty values
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: true

  # Key duplicates
  key-duplicates: enable

  # Key ordering (disabled for Bento - order matters for readability)
  key-ordering: disable

  # Octal values
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true

  # Quoted strings
  quoted-strings:
    quote-type: double
    required: only-when-needed
    allow-quoted-quotes: false

  # Truthy values (yes/no vs true/false)
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
    level: warning

  # New line at end of file
  new-line-at-end-of-file: enable

  # New lines
  new-lines:
    type: unix
